% rereference demonstration to see the impact of rereferencing on data
% note, this demo uses fake data that has a clear component on Channel 1, AF3, but nowhere else
% make by O. Krigolson, Feb 2019
% note, the effect is maximal on Channel 1 but present on Channels 2 AF4,3 AF7,4 AF8,7 C3,
% and 35 Fp1 to some extent. Channels TP9 63 and TP10 60 are also plotted

clear all;
close all;
clc;

load('rereferenceDemoData.mat');

originalData = EEG.data;
timePoints = [1:1:1000];
reference1 = {'TP9' 'TP10'};
reference2 = {'AF3' 'AF4'};
reference3 = {'AVERAGE'};

% lets look at the data before we do anything
figure;
subplot(2,4,1);
plot(timePoints,originalData(1,:));
ylim([-50 50]);
title('AF3');
subplot(2,4,2);
plot(timePoints,originalData(2,:));
ylim([-50 50]);
title('AF4');
subplot(2,4,3);
plot(timePoints,originalData(3,:));
ylim([-50 50]);
title('AF7');
subplot(2,4,4);
plot(timePoints,originalData(4,:));
ylim([-50 50]);
title('AF8');
subplot(2,4,5);
plot(timePoints,originalData(7,:));
ylim([-50 50]);
title('C3');
subplot(2,4,6);
plot(timePoints,originalData(35,:));
ylim([-50 50]);
title('Fp1');
subplot(2,4,7);
plot(timePoints,originalData(63,:));
ylim([-50 50]);
title('TP9');
subplot(2,4,8);
plot(timePoints,originalData(60,:));
ylim([-50 50]);
title('TP10');

pause;

% now, what happens when we reference to the average of the mastoids
reference1Data = doRereference(originalData,reference1,EEG.chanlocs);
figure;
subplot(2,4,1);
plot(timePoints,originalData(1,:));
hold on;
plot(timePoints,reference1Data(1,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: AF3');
subplot(2,4,2);
plot(timePoints,originalData(2,:));
hold on;
plot(timePoints,reference1Data(2,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: AF4');
subplot(2,4,3);
plot(timePoints,originalData(3,:));
hold on;
plot(timePoints,reference1Data(3,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: AF7');
subplot(2,4,4);
plot(timePoints,originalData(4,:));
hold on;
plot(timePoints,reference1Data(4,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: AF8');
subplot(2,4,5);
plot(timePoints,originalData(7,:));
hold on;
plot(timePoints,reference1Data(7,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: C3');
subplot(2,4,6);
plot(timePoints,originalData(35,:));
hold on;
plot(timePoints,reference1Data(35,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: Fp1');
subplot(2,4,7);
plot(timePoints,originalData(63,:));
hold on;
plot(timePoints,reference1Data(63,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: TP9');
subplot(2,4,8);
plot(timePoints,originalData(60,:));
hold on;
plot(timePoints,reference1Data(60,:));
hold off;
ylim([-50 50]);
title('Average Mastoid: TP10');

pause;
% now, what happens when we reference to the average of the mastoids
reference2Data = doRereference(originalData,reference2,EEG.chanlocs);
figure;
subplot(2,4,1);
plot(timePoints,originalData(1,:));
hold on;
plot(timePoints,reference2Data(1,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: AF3');
subplot(2,4,2);
plot(timePoints,originalData(2,:));
hold on;
plot(timePoints,reference2Data(2,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: AF4');
subplot(2,4,3);
plot(timePoints,originalData(3,:));
hold on;
plot(timePoints,reference2Data(3,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: AF7');
subplot(2,4,4);
plot(timePoints,originalData(4,:));
hold on;
plot(timePoints,reference2Data(4,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: AF8');
subplot(2,4,5);
plot(timePoints,originalData(7,:));
hold on;
plot(timePoints,reference2Data(7,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: C3');
subplot(2,4,6);
plot(timePoints,originalData(35,:));
hold on;
plot(timePoints,reference2Data(35,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: Fp1');
subplot(2,4,7);
plot(timePoints,originalData(63,:));
hold on;
plot(timePoints,reference2Data(63,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: TP9');
subplot(2,4,8);
plot(timePoints,originalData(60,:));
hold on;
plot(timePoints,reference2Data(60,:));
hold off;
ylim([-50 50]);
title('Average AF3 AF4: TP10');

pause;
% now, what happens when we reference to the average of the mastoids
reference3Data = doRereference(originalData,reference3,EEG.chanlocs);
figure;
subplot(2,4,1);
plot(timePoints,originalData(1,:));
hold on;
plot(timePoints,reference3Data(1,:));
hold off;
ylim([-50 50]);
title('Average Reference: AF3');
subplot(2,4,2);
plot(timePoints,originalData(2,:));
hold on;
plot(timePoints,reference3Data(2,:));
hold off;
ylim([-50 50]);
title('Average Reference: AF4');
subplot(2,4,3);
plot(timePoints,originalData(3,:));
hold on;
plot(timePoints,reference3Data(3,:));
hold off;
ylim([-50 50]);
title('Average Reference: AF7');
subplot(2,4,4);
plot(timePoints,originalData(4,:));
hold on;
plot(timePoints,reference3Data(4,:));
hold off;
ylim([-50 50]);
title('Average Reference: AF8');
subplot(2,4,5);
plot(timePoints,originalData(7,:));
hold on;
plot(timePoints,reference3Data(7,:));
hold off;
ylim([-50 50]);
title('Average Reference: C3');
subplot(2,4,6);
plot(timePoints,originalData(35,:));
hold on;
plot(timePoints,reference3Data(35,:));
hold off;
ylim([-50 50]);
title('Average Reference: Fp1');
subplot(2,4,7);
plot(timePoints,originalData(63,:));
hold on;
plot(timePoints,reference3Data(63,:));
hold off;
ylim([-50 50]);
title('Average Reference: TP9');
subplot(2,4,8);
plot(timePoints,originalData(60,:));
hold on;
plot(timePoints,reference3Data(60,:));
hold off;
ylim([-50 50]);
title('Average Reference: TP10');